#!/usr/bin/env python

# Injects HTTP request failures for testing purposes.

import os
import httplib
import urllib2
import socket
import random
from main import flickr_to_go

def chaos_urlopen(url, data=None, timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
            cafile=None, capath=None, cadefault=False, context=None):
    if random.randint(0, 9) == 0:
        print('Injecting chaos!')
        raise httplib.BadStatusLine('')
    else:
        return real_urlopen(url, data, timeout, cafile, capath,
            cadefault, context)

real_urlopen = urllib2.urlopen = urllib2.urlopen
urllib2.urlopen = chaos_urlopen

key = os.environ['FLICKR_API_KEY']
secret = os.environ['FLICKR_API_SECRET']
if not flickr_to_go('dest', True, key, secret):
    exit(1)
