#!/usr/bin/env python

import sys
import os
import argparse
from main import flickr_to_go

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--savecreds', action='store_true')
    parser.add_argument('--dest', default='.')
    return parser.parse_args()

def require_env(key):
    if os.environ.has_key(key):
        return os.environ[key]
    else:
        sys.stderr.write("Please set the %s environment variable\n" % key)
        exit(1)


args = parse_args()
key = require_env('FLICKR_API_KEY')
secret = require_env('FLICKR_API_SECRET')
try:
    if not flickr_to_go(args.dest, args.savecreds, key, secret):
        exit(1)
except KeyboardInterrupt:
    exit(1)
